apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    f5tnr: "true"
  name: cafe-coffee
  namespace: default
spec:
  host: cafe.example.com
  path: "/coffee"
  port:
    targetPort: 8080
  tls:
    clientSSL: /Common/clientssl
    reference: bigip
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: coffee-svc