apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: edge-tls
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  tls:
    termination: edge
    clientSSL: /Common/clientssl
    reference: bigip
  hosts:
  - mycrd.example.com