apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: cafe-crd
  namespace: default
  labels:
    f5cr: "true"
spec:
  host: cafe.example.com
  virtualServerAddress: "10.192.125.65"
  virtualServerHTTPSPort: 443
  tlsProfileName: edge-tls
  httpTraffic: redirect
  snat: auto
  pools:
  - monitor:
      interval: 20
      recv: ""
      send: /
      timeout: 10
      type: http
    path: /
    service: tea-svc
    servicePort: 80