apiVersion: v1
kind: Service
metadata:
  name: tea-svc
  namespace: default
  labels:
    app: tea-svc
spec:
  ports:
  - name: tea-svc
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: tea