apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    f5tnr: "true"
  name: cafe-mocha
  namespace: cafenew
spec:
  host: cafenew.example.com
  path: "/mocha"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: mocha-svc