apiVersion: v1
kind: ConfigMap
metadata:
  name: global-cm
  namespace: kube-system
  labels:
    f5nr: "true"
data:
  extendedSpec: |
    extendedRouteSpec:
    - namespace: cafe
      vserverAddr: 10.192.125.65
      vserverName: cafe
      allowOverride: true
    - namespace: cafenew
      vserverAddr: 10.192.125.66
      vserverName: cafenew
      allowOverride: true