apiVersion: v1
kind: ConfigMap
metadata:
  name: global-cm
  namespace: default
  labels:
    f5nr: "true"
data:
  extendedSpec: |
    extendedRouteSpec:
    - namespace: default
      vserverAddr: 10.192.125.65
      vserverName: cafe
      allowOverride: true