
apiVersion: v1
kind: ConfigMap
metadata:
  name: cafe-override
  namespace: default
data:
  template: |
    {
        "declaration": {
            "OpenShift": {
                "Shared": {
                    "https_ose_vserver": {
                        "profileHTTP": {
                            "bigip": "/Common/Custom_HTTP"
                        }
                    }
                }
            }
        }
    }