apiVersion: v1
kind: Service
metadata:
  name: f5-demo-two
  namespace: default
  labels:
    app: f5-demo
spec:
  ports:
  - name: f5-demo
    port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP
  selector:
    app: f5-demo