apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5-demo
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: f5-demo
  template:
    metadata:
      labels:
        app: f5-demo
    spec:
      containers:
      - env:
        - name: service_name
          value: f5-demo
        image: pleshakov/nginx-hello:0.1
        imagePullPolicy: Always
        name: f5-demo
        ports:
        - containerPort: 8080
          protocol: TCP