apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: tea
    spec:
      containers:
      - name: tea
        image: pleshakov/nginx-hello:0.1
        ports:
        - containerPort: 8080