apiVersion: v1
kind: Service
metadata:
  name: tea-svc
  labels:
    app: tea-svc
spec:
  ports:
  - name: tea-svc
    port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP
  selector:
    app: tea-svc